branch_protection_rules:
  - pattern: main
    required_status_checks:
      strict: true
      contexts:
        - "backend"
        - "frontend"
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    enforce_admins: true
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
    restrictions:
      users: []
      teams: []
