"""refactor: move repeaters to separate model files

Revision ID: 15ef9582ec91
Revises: c1f771561492
Create Date: 2025-05-20 16:05:45.234473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ef9582ec91'
down_revision: Union[str, None] = 'c1f771561492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
