"""create products table

Revision ID: 21ddbb72e66e
Revises: dd92ce354c04
Create Date: 2025-05-15 10:45:10.579871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ddbb72e66e'
down_revision: Union[str, None] = 'dd92ce354c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Activation de l'extension uuid-ossp pour la génération d'UUID v4
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('nom_commercial', sa.String(), nullable=False),
    sa.Column('fournisseur', sa.String(), nullable=False),
    sa.Column('ref_formule', sa.String(), nullable=False),
    sa.Column('ref_produit', sa.String(), nullable=True),
    sa.Column('date_mise_marche', sa.Date(), nullable=False),
    sa.Column('resp_mise_marche', sa.String(), nullable=False),
    sa.Column('faconnerie', sa.String(), nullable=False),
    sa.Column('pc_ph', sa.Float(), nullable=True),
    sa.Column('pc_densite', sa.Float(), nullable=True),
    sa.Column('pc_organoleptiques', sa.String(), nullable=True),
    sa.Column('pao_theorique', sa.String(), nullable=True),
    sa.Column('pao_valide', sa.String(), nullable=True),
    sa.Column('util_descr', sa.String(), nullable=True),
    sa.Column('util_precaution', sa.String(), nullable=True),
    sa.Column('tox_nanomaterials', sa.Boolean(), nullable=False),
    sa.Column('ei_signalements', sa.String(), nullable=True),
    sa.Column('autres_tests', sa.String(), nullable=True),
    sa.Column('effets_revendiques', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
